# Generated by Django 5.0 on 2023-12-25 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_goods_price_goods_price_opt'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parametr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, unique=True, verbose_name='Параметр товар')),
            ],
            options={
                'verbose_name': 'Параметр',
                'verbose_name_plural': 'Параметри',
            },
        ),
        migrations.AddField(
            model_name='goods',
            name='parametr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parametr', to='catalog.parametr'),
        ),
    ]
