# Generated by Django 5.0 on 2023-12-12 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('potter', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredients',
            options={'verbose_name': 'Інгредієнт', 'verbose_name_plural': 'Інгредієнти'},
        ),
        migrations.AlterField(
            model_name='ingredients',
            name='identifier',
            field=models.CharField(max_length=50, unique=True, verbose_name='identifier,'),
        ),
    ]
