# Generated by Django 5.0 on 2023-12-20 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('potter', '0002_alter_ingredients_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Elixirs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=50, unique=True, verbose_name='identifier')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Еліксир',
                'verbose_name_plural': 'Еліксири',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='ingredients',
            name='identifier',
            field=models.CharField(max_length=50, unique=True, verbose_name='identifier'),
        ),
    ]
