# Generated by Django 5.0 on 2023-12-20 20:41

import djrichtextfield.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('potter', '0003_elixirs_alter_ingredients_identifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='elixirs',
            name='description',
            field=djrichtextfield.models.RichTextField(blank=True, verbose_name='Опис'),
        ),
    ]
