# Generated by Django 5.0 on 2023-12-21 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('potter', '0005_houses_remove_elixirs_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spells',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=50, unique=True, verbose_name='Identifier')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Закляття',
                'verbose_name_plural': 'Закляття',
            },
        ),
        migrations.AlterField(
            model_name='elixirs',
            name='identifier',
            field=models.CharField(max_length=50, unique=True, verbose_name='Identifier'),
        ),
        migrations.AlterField(
            model_name='houses',
            name='animal',
            field=models.CharField(max_length=50, verbose_name='Animal'),
        ),
        migrations.AlterField(
            model_name='houses',
            name='element',
            field=models.CharField(max_length=50, verbose_name='Element'),
        ),
        migrations.AlterField(
            model_name='houses',
            name='founder',
            field=models.CharField(max_length=50, verbose_name='Founder'),
        ),
        migrations.AlterField(
            model_name='houses',
            name='houseColours',
            field=models.CharField(max_length=50, verbose_name='HouseColours'),
        ),
        migrations.AlterField(
            model_name='houses',
            name='identifier',
            field=models.CharField(max_length=50, unique=True, verbose_name='Identifier'),
        ),
        migrations.AlterField(
            model_name='ingredients',
            name='identifier',
            field=models.CharField(max_length=50, unique=True, verbose_name='Identifier'),
        ),
    ]
